[colors.bright]
black = "#000000"
red = "#D75F5F"
green = "#87D787"
yellow = "#D7AF87"
blue = "#f38d70"
magenta = "#D787D7"
cyan = "#5BA6A6"
white = "#8A8A8A"

[colors.normal]
black = "#000000"
red = "#D75F5F"
green = "#99bc80"
yellow = "#D7AF87"
blue = "#f38d70"
magenta = "#D787D7"
cyan = "#5BA6A6"
white = "#8A8A8A"

[colors.primary]
background = "#2c2d30"
foreground = "#B2B2B2"

[font]
size = 16.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[env]
term = "xterm-256color"
save_to_clipboard = "true"
